name: contrad
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1
  - imageio
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - python=3
  - pytorch
  - scipy
  - tensorflow-gpu=1.14
  - termcolor
  - torchvision
  - tqdm
  - pip:
    - gin-config==0.3.0
    - gpustat
    - psutil
    - tensorboardx
    - kornia

